### ISSUE TITLE
Trace Explorer and Trace Viewer tabs out of sync

### ISSUE THREAD

**Issue by PatrickTasse** [theia-ide/theia-trace-extension#149] opened 2020-10-09 20:04 UTC
From what I can gather:

- The Trace Explorer shows experiments that are opened in the trace server
- The Open Trace command in the file Explorer will open a Trace Viewer tab
- The initialisation of the Trace Viewer tab will create and/or open the experiment in the trace server, which should add it to Trace Explorer
- Closing a Trace Viewer tab will close and delete the experiment in the trace server, which should remove it from Trace Explorer
- When the browser is closed and reopened, its previously opened Trace Viewer tabs will be restored, and their initialisation will create and/or open the experiment in the trace server

Some observations:
- When opening a new browser tab, sometimes the Trace Explorer experiments are restored, sometimes they are not. Sometimes the Trace Viewer tabs are restored, sometimes they are not.
- It can happen that a Trace Explorer experiment is visible, but it has no corresponding Trace Viewer tab.
- It can happen that selecting a Trace Explorer experiment will populate the Available Analysis, sometimes not
- It can happen that after closing a Trace Viewer tab in one browser tab (experiment is removed from the Trace Explorer), then opening a new browser tab the removed experiment comes back in the new browser tab's Trace Explorer.
- If the trace server is killed then a Trace Viewer tab is closed, then the experiment does not come back after relaunching and reconnecting to the trace server. However the experiment's internal files are lingering in the trace server.

I see two approaches going forward with the Trace Explorer:

1) show Opened experiments

- At initialisation of the Trace Explorer then all opened experiments should have a corresponding Trace Viewer tab created, if one has not already been restored.
- When fetching the experiments from the trace server, all created experiments should be opened if not already opened, and returned.

2) show Created experiments

- Trace Explorer shows all created experiments whether they are opened or not.
- Need a new TSP request that returns created experiments.
- "Open" context menu and/or double-click on an experiment will open it.
- "Delete" context menu on an experiment to delete it from the trace server and remove it from the Trace Explorer.
- Closing a Trace Viewer tab only closes the experiment, does not delete it.
- Need a new TSP request to close an experiment.

**Comment by bhufmann** [comment] 2020-10-15 18:55
Releated to #140

**Comment by bhufmann** [comment] 2020-10-15 19:09
Thanks for the elaborate description and suggestions. I think this items needs to be split in multiple sub-issues to track it easilier.

**Comment by mirsky-work** [comment] 2020-12-08 15:39
For the MVP we'll implement the FE parts of proposal 2 above, without handlining closing an experiment on the server.

@ebugden, thoughts on the UX changes (adding context menu for the experiments list)?

**Comment by ebugden** [comment] 2020-12-09 20:12
I'm a little thrown off by how single traces are closed differently from experiments. Why are experiments not deleted when their tab is closed? Because they're not saved anywhere right now and users would have to create them from scratch?

**Comment by mirsky-work** [comment] 2020-12-10 17:41
> I'm a little thrown off by how single traces are closed differently from experiments.
It's the same.

> Why are experiments not deleted when their tab is closed? Because they're not saved anywhere right now and users would have to create them from scratch?
Today, closing a tab is (usually) deleting the experiment, with the exception of closing it immediately after opening, in which case an experiment entry might be added to the Trace Explorer after the tab was already closed (leaving no way to close it).

**Comment by ebugden** [comment] 2020-12-14 17:46
>> **ebugden:** I'm a little thrown off by how single traces are closed differently from experiments.
>
>**mirsky-work:** It's the same.

If experiments and single traces are both closed by closing the tab then I don't see why the context menu for the experiments list is required for deleting experiments.

> **mirsky-work:** Today, closing a tab is (usually) deleting the experiment, with the exception of closing it immediately after opening, in which case an experiment entry might be added to the Trace Explorer after the tab was already closed (leaving no way to close it).

If the issue is that experiments do not close automatically if the tab is closed before the experiment loads, then adding a context menu to compensate for this edge case does not seem like a good solution. Is there a way to cancel the experiment opening operation when the tab is closed?

**Comment by PatrickTasse** [comment] 2020-12-14 20:42
The trace/experiment consumes both memory resources (trace instance) and disk resources (workspace elements, supplementary files) in the trace-server when it is opened. We can free the memory resources when the tab is closed. But if we only rely on the tab closing to free the disk resources, then you might miss the opportunity to do so if the tab is closed while the trace-server is down. Then there would be no way to free those resources, except maybe with a background cleanup job, or automatically deleting a trace/experiment for which no tab is opened when handling the response of the periodic fetchExperiments?

One advantage of keeping created trace/experiments is that you could open and close back and forth a few traces that you are currently working on, without needed to rerun their indexing and analyses on the trace server, and without the user needing to go find them again in the file system open menu. Then you manually delete them when you are done.

**Comment by ebugden** [comment] 2020-12-17 00:30
> **Patrick Tasse:** if we only rely on the tab closing to free the disk resources, then you might miss the opportunity to do so if the tab is closed while the trace-server is down. Then there would be no way to free those resources

Good point. And and if I understand correctly the risk of trapping resources applies to both single traces and experiments. 

**Why don't we make manual deletion via context menu the only way to close both single traces and experiments?** It's a valid UX choice that makes closing consistent and it sounds like it solves the issues with accidentally trapping resources. 

> **Patrick Tasse:** One advantage of keeping created trace/experiments is that you could open and close back and forth a few traces that you are currently working on, without needed to rerun their indexing and analyses on the trace server, and without the user needing to go find them again in the file system open menu. Then you manually delete them when you are done.

I agree that manually deleting both single traces and experiments is what users are probably expecting. When comparing and contrasting several data sources and spending a lot of time tweaking layouts and filters you don't expect it to be so easy to accidentally delete your hard work (ex. closing a tab).

**Comment by PatrickTasse** [comment] 2020-12-18 17:58
> **Why don't we make manual deletion via context menu the only way to close both single traces and experiments?** It's a valid UX choice that makes closing consistent and it sounds like it solves the issues with accidentally trapping resources.

The user would only have the option to delete the experiment (or whatever it ends up being called), which may contain one or many traces. The trace resources will be deleted automatically by the trace-server when it is no longer in use by any remaining experiments. Or to be exact, the client will always ask the trace-server to delete the trace(s) but the trace-server will reject the request if the trace is still in use by another experiment.

**Comment by ebugden** [comment] 2020-12-24 17:04
I think we may be misunderstanding each other. In my question, "Why don't we make manual deletion via context menu the only way to close both single traces and experiments?" I was referring to traces that are not part of experiments. 

For example, below you could "right-click --> delete" on Trace 1 and Trace 2, but not on Trace 3 and Trace 4 because they're part of an experiment: 
![image](https://user-images.githubusercontent.com/28311615/103100294-e9f36c80-45df-11eb-99b9-bef2135de197.png)

**Closed** 2021-02-23 14:54 UTC
Labels: Theia UI, UX, enhancement
