### ISSUE TITLE
Consider alternatives for graphics acceleration

### ISSUE THREAD

**Issue by mad-season** [theia-ide/theia-trace-extension#122] opened 2020-09-17 02:06 UTC
Both the timeline-chart and the timegraph use PIXI (which uses WebGL) for graphics acceleration at scale.

Imho, there are two major problems with this:
WebGL needs GPU's to provide any useful benefit. But requiring GPU's to run performant theia-trace-extension is an obstacle to adoption. Many users work on virtual machines run on bare metal powered by server-class processors. These processors oftentimes do not have on-chip graphics and upgrading machines is big $$$.

When there is no GPU, WebGL uses the CPU for rendering shapes. Like A LOT. Again, in the common case where several VM's run on a single server-class machine, a trace-extension user may end up abusing CPU resources thus impacting others working on the same machine.

My ask (and it is a big one). 

```
if(gpu_found) {
    use PIXI for rendering charts;
} else {
    useNonWebGLLibs to render charts;
}
```

@bhufmann @marcdumais-work @MatthewKhouzam please opine.

**Comment by marcdumais-work** [comment] 2020-09-17 14:44
Something to consider, going forward: I think PIXI is a browser-side library, and that the performance problem when GPU acceleration is not available would be mostly applicable to the Electron version of Theia apps, where the Electron-builtin Chromium runs in the same env as the Theia app backend, and is subject to the limitations of that environment. I assume that running locally on the user's laptop, it should not be a problem generally (even the Intel-builtin GPU should be decent enough?). 

When running the "browser" version of the same app, the browser runs in the user's environment (laptop) whether the backend runs in a VM, container or whatnot should, in theory, have no impact on whether WebGL or software rendering is used (to be confirmed). 

So maybe this is mostly a "transition" issue: in the future the Electron version of Theia apps will tend to be used mostly used on user's laptops, that have WebGL available. Centralized solutions will tend to be running the browser version of the same app, and in that case the user's browser will determine if WebGL is available.

WDYT?

**Comment by bhufmann** [comment] 2020-09-17 15:09
I see your points when GPU support is not available and I agree that the situation needs to be addressed since PIXI is used for some core visualizations (timeline-chart) that are used a lot in the trace-extension. Other types of visualization don't require PIXI and GPU support.

Here are 3 suggestions for investigations:
- Profile the timeline-chart and understand why it takes so much CPUs when GPUs are not available. 
- Try to understand if there is something that can be done in the timeline-chart code in how pixi is used. Maybe the timeline-chart code can be changed that would improve the situation. 
- Investigate alternative libraries and their performance (e.g. in respect to drawing many objects). We already know that SVG based libraries are not an option for the timeline-chart.

Any thoughts to that?

**Comment by mad-season** [comment] 2020-09-17 15:42
@marcdumais-work Yes, if the users can run the trace-extension in a browser on their laptops then webgl acceleration will not be a concern.

The thing is the user's environment may not always be their laptop...some users may be **required** to work on server class machines. In addition, even if all users are allowed to run the trace-extension on their laptops in a browser, they simply may not choose to since the rest of their workflow is in their VM.

@bhufmann good suggestions all of them.

**Comment by tahini** [comment] 2020-09-17 15:56
Just for the record, I have a laptop (not my development machine, but still quite recent, nothing fancy, just normal ubuntu 18.04) on which, when I run the trace extension as a vscode extension, I get an unsupported webGL exception that causes the trace extension to not work at all.

The exact exception is as follows: Uncaught Error: WebGL unsupported in this browser, use "pixi.js-legacy" for fallback canvas2d support.

I'll investigate this issue in more details later.

**Comment by marcdumais-work** [comment] 2020-09-17 17:19
> use "pixi.js-legacy" for fallback canvas2d support.

Maybe this is what should be used for fallback. I guess we do not, yet? 

@mad-season I wonder why it still kind of works for you without WebGL, rather than just not working at all, like for @tahini

**Comment by bhufmann** [comment] 2020-09-17 18:05
> The exact exception is as follows: Uncaught Error: WebGL unsupported in this browser, use "pixi.js-legacy" for fallback canvas2d support.

I get the same error when running the Electron version of the theia-trace-extension in a similar environment that @mad-season described. No timeline-chart nor other charts (XY or events table) are populated. 

I think, the reason why other charts don't work is caused by the time-axis. The axis is implemented in the timeline-chart library which uses Pixi.

**Comment by mad-season** [comment] 2020-09-17 23:47
@marcdumais-work running the trace-extension on my Linux VM using Chrome75 does in fact use WebGL 1. The problem is that the mere act of opening the Resources Status view kicks cpu utilization from < 5% per cpu to an absurd 70% per cpu.

Upon closing the view **and** the trace, the per CPU utilization goes...wait for it...to 80%!! The only way I am able to pull down the CPU usage back to a sensible value is by closing the workspace.

Moving on to firefox80, I see similar behavior. There are many webgl warnings thrown by PIXI though...

WebGL context was lost. isWebGLSupported.ts:44:36
Failed to create WebGL context: WebGL creation failed: 

tryNativeGL
Exhausted GL driver options. getTestContext.ts:24:24
Failed to create WebGL context: WebGL creation failed: 

tryNativeGL
Exhausted GL driver options. ContextSystem.ts:160:24
Failed to create WebGL context: WebGL creation failed: 

tryNativeGL
Exhausted GL driver options. ContextSystem.ts:160:24

root INFO PixiJS 5.3.3 - WebGL 1 - http://www.pixijs.com/ logger-protocol.ts:112:15

Failed to create WebGL context: WebGL creation failed: 
tryNativeGL
Exhausted GL driver options. ContextSystem.ts:160:24

There is something happening here. What it is ain't exactly clear...

**Comment by mad-season** [comment] 2020-09-17 23:50
@bhufmann @tahini it is possible that the electron app is using browser versions that are too old. Try upgrading the app to use newer versions. The exception will most likely go away.

**Comment by tahini** [comment] 2020-09-18 00:32
Probably, but I don't want it to go away! This is what some of our users may get. I'd rather fix it so it works in all cases, with hopefully decent performances, or workaround to get them (like visible-lines-only drawing, default to lower resolutions with easily-accessible options to increase it as necessary). So for now, I'll keep my "legacy" environment for quality control!

**Comment by bhufmann** [comment] 2020-09-18 01:12
To use the CanvasRenderer (no WebGL 1/2) we need to import pixi.js-legacy in the source files. If WebGL 1/2 is not available it would automatically fallback to the CanvasRenderer. If we'd like to test the CanvasRenderer, then we could instantiate the pixi application with the "forceCanvas" flag (new PIXI.Application({forceCanvas: true}))). Would be interesting to see how the performance is then.

**Comment by mad-season** [comment] 2020-09-18 01:32
@tahini the chromium version that the electron app uses will need to be bumped up.

@marcdumais-work is this easy to do for theia-based IDE's? I am not sure...

**Comment by tahini** [comment] 2020-09-18 18:02
I made this PR in timeline-chart https://github.com/theia-ide/timeline-chart/pull/41

It fixes my issue with older WebGL support. But I'm no expert with WebGL acceleration. I don't know if it has an impact on modern browsers, but in this thread, someone says it should not (https://stackoverflow.com/questions/61638676/create-legacy-fallback-for-pixi-js). Also, I haven't checked performances at all, just fixed a problem ;-)

**Comment by marcdumais-work** [comment] 2020-09-18 23:34
@tahini I think you've got the best way forward, if indeed the performance of the software library is decent.

In an offline discussion with @mad-season we confirmed that in his environment WebGL is provided in software, in the virtual video card driver. This has to be very inefficient since it's using a CPU to execute a workload that was meant for a GPU. It explains the low performance. But with the PR above there should be good improvement. I think on Gitpod it should be much better too (the Electron version is used ATM, accessed with VNC).

**Comment by marcdumais-work** [comment] 2020-09-18 23:53
> I made this PR in timeline-chart theia-ide/timeline-chart#41

@tahini The performance looks good and I see no difference visually. :+1: 

I think a `next` version of `timeline-chart` will be automatically published to `npm` when your PR is merged?

**Comment by tahini** [comment] 2020-09-25 19:33
Can we close this issue?

**Comment by ankusht-work** [comment] 2020-09-25 20:31
@tahini : I am working on a patch that will detect WebGL version on the user's machine and will set the forcecanvas flag accordingly. I will create a PR for it and will link this issue.

**Comment by mirsky-work** [comment] 2021-08-05 20:46
I believe theia-ide/timeline-chart#48 fixes the issues we experienced internally. Closing.

**Closed by mirsky-work** 2021-08-05 20:46 UTC
