### ISSUE TITLE
Support tree/table data in Theia

### ISSUE THREAD

**Issue by tahini** [theia-ide/theia-trace-extension#18] opened 2020-05-25 15:47 UTC
Some data providers only provide tree or table data (no time line required). The respective outputs should be displayed properly.

**Comment by ebugden** [comment] 2021-09-30 20:15
@bhufmann Can this be closed? Does this refer to views like the Events Table?

**Comment by bhufmann** [comment] 2021-10-01 14:47
> @bhufmann Can this be closed? Does this refer to views like the Events Table?

No, it cannot be closed because it refers to data providers of type DATA_TREE, which is used, for example the Trace Compass function duration statistics.

**Comment by ebugden** [comment] 2021-11-29 20:34
@bhufmann Is this a duplicate of #144? Can it be closed?

**Comment by bhufmann** [comment] 2021-11-29 20:38
yes, it's a duplicate and can be closed

**Closed by bhufmann** 2021-11-29 20:38 UTC
Labels: Theia UI
