### ISSUE TITLE
Clicking on trace file to change tab focus opens duplicate tab

### ISSUE THREAD

**Issue by ebugden** [theia-ide/theia-trace-extension#450] opened 2021-08-16 19:19 UTC
If the trace is already open in a tab, clicking the trace file in "Opened Traces" should just select the existing tab. 

In the video:

* **0:06** - Click to change tab highlight from "apt" trace to "201-lttng-userspace-tracing" trace that is already open in a tab --> Duplicate tab created.
* **0:14** - Click to change tab highlight from "apt" trace to "201-lttng-userspace-tracing" trace that is already open in a tab (and already has a duplicate) --> No additional duplicate created. This only happens once (only one duplicate is ever created).
* **0:18** - Duplicate "apt" tab created.

https://user-images.githubusercontent.com/28311615/129616513-063f849e-14f8-4090-b11f-788e7540d44b.mp4

**Browser:** Chrome (version 92.0.4515.131)

**Comment by mirsky-work** [comment] 2021-08-17 16:14
I believe it's a duplicate of #364.

**Closed** 2021-10-19 19:21 UTC
Labels: bug
